spring:
  application:
    name: kafka-avro
  kafka:
    bootstrap-servers: "127.0.0.1:9092"
    producer:
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      properties:
        schema:
          registry:
            url: "http://127.0.0.1:8081"
    consumer:
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      auto-offset-reset: "earliest"
      group-id: "learn-avro-id"
      properties:
        schema:
          registry:
            url: "http://127.0.0.1:8081"
        specific :
          avro:
            reader: "true"

server:
  port: 8080

kafka:
  topic:
    name: learn-avro
  partition: 3
  replicate: 1